Repository tensorflow/tfjs-converter, pull requests merged in 2019-06, with the labels that each got.

#381 pin tensorflow 2 nightly version to date 06/08
  python/requirements.txt
Labels: cla: yes

#378 Update tfjs-converter to 1.2.1.
  package.json
  python/tensorflowjs/version.py
  src/version.ts
  yarn.lock
Labels: INTERNAL, cla: yes

#380 add the ComplexAbs op support
  docs/supported_ops.md
  src/operations/executors/basic_math_executor.ts
  src/operations/executors/basic_math_executor_test.ts
  src/operations/op_list/basic_math.ts
Labels: cla: yes

#384 Add support for FusedBatchNormV3
  docs/supported_ops.md
  src/operations/executors/normalization_executor.ts
  src/operations/executors/normalization_executor_test.ts
  src/operations/op_list/normalization.ts
Labels: cla: yes

#382 added support complex op
  docs/supported_ops.md
  src/operations/executors/basic_math_executor.ts
  src/operations/executors/basic_math_executor_test.ts
  src/operations/op_list/basic_math.ts
Labels: cla: yes

#387 fixed python test error
  python/requirements.txt
Labels: cla: yes

#385 [1.2.x] Bump numpy version
  package.json
  python/requirements.txt
  python/tensorflowjs/version.py
  src/version.ts
Labels: cla: yes

#389 move the tensorflow deps to 1.14
  python/requirements.txt
  python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#390 Add snippet testing to cloud build.
  cloudbuild.yml
  package.json
  scripts/test_snippets.ts
  src/operations/custom_op/register.ts
Labels: cla: yes

#383 Add support for Hub V2 modules conversion.
  python/requirements.txt
  python/tensorflowjs/converters/converter.py
  python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#391 Update tfjs-converter to 1.2.2.
  package.json
  yarn.lock
Labels: INTERNAL, cla: yes

#392 fix a typo on guess output format from input format
  python/tensorflowjs/converters/converter.py
Labels: cla: yes

#386 Add support for string weights
  python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  python/tensorflowjs/read_weights.py
  python/tensorflowjs/read_weights_test.py
  python/tensorflowjs/write_weights.py
  python/tensorflowjs/write_weights_test.py
  src/executor/graph_executor.ts
Labels: cla: no
